# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
   gym(scheme: "AppScheme”,
    #output_name 指打包完成后, 输出ipa文件的名字
	output_name: "PullFresh_Debug”,
    #export_method 打包版本选择
    #分别是app-store、ad-hoc、development、enterprise
	export_method: "development”,
    	export_options: {
      	  provisioningProfiles: { 
          #左侧表示你的项目的bundle id
          #右侧表示你的项目在选择export_method后,对应的描述文件名字
          "com.man.PullRefresh" => "ProfilesName"
        }
       }) 

  end
end
